- name: varibales from Play Level
  hosts: localhost
  tasks: 
  - name: checking passenger details using variables from inventory
    ansible.builtin.debug:
      msg: " list of Animals in Zoo {{NAME}}, and its {{GENDER}}"