- name: variables from arguments
  hosts: localhost
  tasks: 
  - name: checking passenger details using variables from inventory
    ansible.builtin.debug:
      msg: "Animals in Zoo {{NAME}}, and its {{GENDER}}"