#using conditions 
- name: conditions
  hosts: localhost
  tasks: 
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop #id roboshop is a linux command 
    register: User #user is a variable name so that output will be stored in user 
  
  - name: print variable value
    ansible.builtin.debug: #it is a module to debug and above builtin.command is also a module
      msg: "user output: {{User}}" 