#using conditions 
- name: conditions
  hosts: localhost
  become: yes #to create user if not found then we need to be a root user
  tasks: 
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop #id roboshop is a linux command 
    register: user #user is a variable name so that output will be stored in user 
    ignore_errors: true #ansible will not exit from playbook while executing even there is an error
  
  - name: print variable value
    ansible.builtin.debug: #it is a module to debug and above builtin.command is also a module
      msg: "user output: {{user}}" 

  - name: print exit status or return code 
    ansible.builtin.debug: #
      msg: "status is: {{user.rc}}" 

  - name: create user 
    ansible.builtin.user: #it is  user module
      name: roboshop
    when: user.rc != 0 #0 means success which means user is there then only the condition should run and create a user other than 0 is no user with name roboshop
       
